:sectnums:
= Introduce the environment


*ansible-navigator* has been built to fit into common developer workflows and will be used from within the https://github.com/cdr/code-server[code-server, window=_blank] integrated terminal.

NOTE: *code-server* is not packaged with Ansible Automation Platform and is not at all affilliated with Red Hat***

. Integrated terminal
+
* Open the integrated terminal *Terminal > New Terminal* and:
* Quickly test that navigator has been installed, run:
+
[source,shell]
----
ansible-navigator --help
----



. Now that we know *ansible-navigator* was installed successfully, try writing a quick playbook called *test.yml* to ping localhost. It could look something like this:
+
[source,yaml]
----
---
- name: this is just a test
  hosts: localhost
  gather_facts: true
  tasks:

  - name: ping test
    ping:
----

. Now, run it with `ansible-navigator`:
+
[source,shell]
----
ansible-navigator run ./test.yml -m stdout
----
+
.You should be looking at something like this (and looking very much like ansible-playbook output)
[source,shell]
----
[WARNING]: provided hosts list is empty, only localhost is available. Note that
the implicit localhost does not match 'all'

PLAY [this is just a test] *****************************************************

TASK [Gathering Facts] *********************************************************
ok: [localhost]

TASK [ping test] ***************************************************************
ok: [localhost]

PLAY RECAP *********************************************************************
localhost : ok=2    changed=0    unreachable=0    failed=0    skipped=0    rescued=0    ignored=0
----

+
NOTE: *-m stdout* will run in standard out mode which will display execution results just like *ansible-playbook*
